version: "3.8"

services:

  postgresql:
    image: postgres:17
    container_name: invoice_management_postgresql
    ports:
      - "5433:5432"
    restart: always
    environment:
      - POSTGRES_DB=invoicedb
      - POSTGRES_USER=invoice
      - POSTGRES_PASSWORD=XakH4FE7uASdwIrkhint6jbjEHkMKiWU
    volumes:
      - invoicedb-data:/var/lib/postgresql/data
    networks:
      - invoice-management

volumes:
  invoicedb-data:

networks:
  invoice-management: